### ISSUE TITLE
Question about that right code outline panel

### ISSUE THREAD

**Issue by michaellee8** [ray-x/nvim#1]
Hi there, this is really a nice piece of config. I have been trying to do something like this for long but no success.

Just one small question here. I can see that you have a code oultine panel in the right-hand side. How do you get that? It deos not really looks like what TagBar provides, is that based on LSP or treesitter. I have recently been trying to find some replacement of tagbar for developing with dart since dart doesn't has the best ctag support.

**Comment by ray-x** [comment]
I think you mean vista (https://github.com/liuchengxu/vista.vim). It can be config to be either LSP mode or ctag mode.

**Comment by michaellee8** [comment]
This is what I need. Thank you so much.
