### ISSUE TITLE
Areal Initialization Errors

### ISSUE THREAD

**Issue by flamedmg** [ray-x/nvim#13]
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/416393/149305051-b2ba3c1d-8ea5-4f38-a5b1-39a48fd08111.png">

**Comment by flamedmg** [comment]
while investigating keymaps i found many more errors. I was not able to make commenting/uncommenting to work
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/416393/149305283-fa3684cb-c221-40a5-9f5d-f3d75c30af32.png">
Here what i see when pressing cmd-/

**Comment by ray-x** [comment]
Thanks. Those issues should be fixed. I only use Comment in visual mode and did not notice they changed the API.
