### ISSUE TITLE
Problems when installing from scrach

### ISSUE THREAD

**Issue by eremid** [ray-x/nvim#15]
Hello,

I've got an issue with navigator.lua or windline... or me when I try to install this repo from scratch.
What am i missing ? Thanks for you help, 
Regards

```
Error executing vim.schedule lua callback: ...e/pack/packer/opt/windline.nvim/lua/wlfloatline/init.lua:79: Vim(lua):E5108: Error executing lua ...er/opt/navigator.lua/lua/navigator/lspclient/clients.lua:445: attempt to index a function value
stack traceback:
	...er/opt/navigator.lua/lua/navigator/lspclient/clients.lua:445: in function 'lsp_startup'
	...er/opt/navigator.lua/lua/navigator/lspclient/clients.lua:700: in function 'setup'
	...er/opt/navigator.lua/lua/navigator/lspclient/clients.lua:735: in function 'on_filetype'
	[string ":lua"]:1: in main chunk
	[C]: in function 'nvim_set_current_win'
	...e/pack/packer/opt/windline.nvim/lua/wlfloatline/init.lua:79: in function 'create_floating_win'
	...e/pack/packer/opt/windline.nvim/lua/wlfloatline/init.lua:521: in function 'setup'
	/Users/me/.config/nvim/lua/core/lazy.lua:170: in function 'fn'
	vim.lua:415: in function 'cb'
	vim.lua:285: in function <vim.lua:285>
stack traceback:
	[C]: in function 'nvim_set_current_win'
	...e/pack/packer/opt/windline.nvim/lua/wlfloatline/init.lua:79: in function 'create_floating_win'
	...e/pack/packer/opt/windline.nvim/lua/wlfloatline/init.lua:521: in function 'setup'
	/Users/me/.config/nvim/lua/core/lazy.lua:170: in function 'fn'
	vim.lua:415: in function 'cb'
	vim.lua:285: in function <vim.lua:285>
```

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilé par brew@Monterey
macOS 12.1

**Comment by ray-x** [comment]
Thanks for reporting.
That is because I pushed some testing code of `navigator.lua` experiential feature. Sorry for that. It should be fixed

**Comment by eremid** [comment]
Hello, thanks for your quick fix.
I've got this one now :
`packer.nvim: Error running config for navigator.lua: [string "..."]:0: attempt to call global 'Plugin_folder' (a string value)`

**Comment by ray-x** [comment]
Sorry. It was not fixed. Just push another commit.

**Comment by eremid** [comment]
I did a :

- git pull in ~/.config/nvim
- packer compile in nvim

Same issue.
Thanks

**Comment by ray-x** [comment]
There is no Plugin_folder reference in the code.  Would you recompile the Packer a few times and check if the issue exists or not? In lots of cases compiling the packer one time does not clean up the cache.

**Comment by eremid** [comment]
OK it works with a full re-install from scratch.

Thanks again !
