### ISSUE TITLE
Avoiding LSP formatting conflicts

### ISSUE THREAD

**Issue by eremid** [ray-x/nvim#17]
Hello,

How can I force a lsp server on file save ? For example, formating by default with null-ls on my go files.
I tried to add this lines but without success :
https://github.com/jose-elias-alvarez/null-ls.nvim/wiki/Avoiding-LSP-formatting-conflicts

<img width="507" alt="save" src="https://user-images.githubusercontent.com/6757944/154472396-b9a0a5d0-f7c9-405b-bd41-61a83a109bea.png">

Thanks for help !
Regards

**Comment by ray-x** [comment]
gopls format capacity should be disabled.
e.g in go.nvim, you can set ` lsp_document_formatting = false`

In navigator, you can also disable with
```
      disable_format_cap = { "gopls"  }

```

**Comment by eremid** [comment]
Thanks.
It's not already there ?
https://github.com/ray-x/nvim/blob/69b2d2d6649806e2af0048e376aed6239f7a800f/lua/modules/lang/config.lua#L307
https://github.com/ray-x/nvim/blob/69b2d2d6649806e2af0048e376aed6239f7a800f/lua/modules/lang/config.lua#L393

**Comment by eremid** [comment]
It's ok now ! Thanks a lot.
