### ISSUE TITLE
Tabnine config by lazy loading

### ISSUE THREAD

**Issue by mkubasz** [ray-x/nvim#18]
Hi, I have an issue to load tabnine.

This is my loader below cmp.setup

`require("packer").loader('cmp_tabnine')
  local tabnine = require('cmp_tabnine.config')`

and how I install plugin.

    `{ "tzachar/cmp-tabnine", run="./install.sh", opt = true },`
    
    Maybe you have the experience loading lazy tabnine which works?

**Comment by vsedov** [comment]
you can do it on filetype maybe? So inside the cmp setup you can make a use_tabnine_function that contains valid filetypes that can load tn. 
so you could do 
```
if vim.o.ft == "python" then
	require("packer").loader('cmp_tabnine')
    table.insert(sources, { name = "cmp_tabnine", priority = 9 })
end
```

**Comment by mkubasz** [comment]
@vsedov 
`function config.nvim_cmp()
  local cmp = require("cmp")
	require("packer").loader('cmp_tabnine')

  cmp.setup({

    sources = cmp.config.sources({
      { name = 'cmp_tabnine' },
  })

if vim.o.ft == "python" then
	require("packer").loader('cmp_tabnine')
    table.insert(sources, { name = "cmp_tabnine", priority = 9 })
end
  local tabnine = require('cmp_tabnine.config')
  tabnine:setup({
    max_lines = 1000;
    max_num_results = 20;
    sort = true;
    run_on_every_keystroke = true;
    snippet_placeholder = '..';
    show_prediction_strength = false;
  })
end`
This part still has issue with plugin 
 • cmp-tabnine (not loaded)

**Comment by vsedov** [comment]
Works fine for me 

```lua
completion["hrsh7th/nvim-cmp"] = {
    -- opt = true,
    event = { "InsertEnter", "CmdLineEnter", "InsertCharPre" }, -- InsertCharPre Due to luasnip
    -- ft = {'lua', 'markdown',  'yaml', 'json', 'sql', 'vim', 'sh', 'sql', 'vim', 'sh'},
    after = { "LuaSnip" }, -- "nvim-snippy",
    requires = {
        {
            "tzachar/cmp-tabnine",
            run = "./install.sh",
            -- after = "nvim-cmp",
            config = conf.tabnine,
            opt = true,
        },````

function config.tabnine()
    local tabnine = require("cmp_tabnine.config")
    tabnine:setup({
        max_line = 1000,
        max_num_results = 20,
        sort = true,
        run_on_every_keystroke = true,
    })
end


if vim.o.ft == "python" then
    require("packer").loader("cmp-tabnine")
    table.insert(sources, { name = "cmp_tabnine", priority = 9 })
end
````

**Comment by mkubasz** [comment]
Thanks that helps me a lot :)

**Comment by ray-x** [comment]
thanks @vsedov for the comments.
BTW, personally, tabnine uses lots of CPU. mkubasz, maybe you can check if codepiloit works for you.

**Comment by mkubasz** [comment]
@ray-x Lucky for me, my team buy a version using the cloud. Which uses less CPU. But copilot definitely is on my list
