### ISSUE TITLE
Please add install instructions

### ISSUE THREAD

**Issue by bbkane** [ray-x/nvim#2]
Hello! I'd love to try this config, but I'm not sure what dependencies it has :)

Could you please add an "install" section?

**Comment by ray-x** [comment]
I added install instructions. Please check if it works for you.
I am not sure if the instructions work in your OS. I am using MacOS btw.

**Comment by bbkane** [comment]
I'm using MacOS and getting the following error:

```
Error detected while processing VimEnter Autocommands for "*":
E5108: Error executing lua [string ":lua"]:1: module 'packer.load' not fo
und:
        no field package.preload['packer.load']
        no file './packer/load.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lu
ajit-2.1.0-beta3/packer/load.lua'
        no file '/usr/local/share/lua/5.1/packer/load.lua'
        no file '/usr/local/share/lua/5.1/packer/load/init.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lu
a/5.1/packer/load.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lu
a/5.1/packer/load/init.lua'
        no file './packer/load.so'
        no file '/usr/local/lib/lua/5.1/packer/load.so'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/lib/lua/
5.1/packer/load.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './packer.so'
        no file '/usr/local/lib/lua/5.1/packer.so'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/lib/lua/
5.1/packer.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```

I don't know much about lua. Do I need to install something else?

**Comment by ray-x** [comment]
Hi, bbkane
Thanks for trying this out. It turned out to be a bug in my script. As I did not purge my folder and re-run the script from ground up.
The bug was fixed and please give it another try.

If you do not want start from beginning, you can 
(1) pull the repo
(2) Run the commands in nvim command mode. 
:PackerCompile
:PackerUpdate

Thanks!

**Comment by bbkane** [comment]
Apologies for the late reply @ray-x . I'm off vacation and back at work, so I'm not sure when I'll have time to play with this. I'll go ahead and close this ticket, and open a new one if I have troubles when I have time to check this out again :)
