### ISSUE TITLE
[Q] Neovim 0.8 issue with lsp

### ISSUE THREAD

**Issue by mkubasz** [ray-x/nvim#21]
I found a new issue after migration. Maybe someone has a similar 'Error executing vim.schedule lua callback: vim/keymap.lua:0: rhs: expected string|function, got nil'

**Comment by ray-x** [comment]
Are you working on the most recent commits?
I have not seen this in the last few weeks. I use the latest neovim so I assume it is a bit ahead of 0.8.0

**Comment by mkubasz** [comment]
I use homebrew neovim :D Magic upgrade from 0.7. will crash my setup in the term of lsp.

**Comment by ray-x** [comment]
what is the git hash of your current nvim config?
Could you send more detail info on the stack trace?

**Comment by mkubasz** [comment]
I fixed it. The issue was related to the new API vim.diagnostic which changed in neovim 0.8.  I created a new keymap. Sorry for the trouble.
