### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by SingularisArt** [ray-x/nvim#22]
Hello, ray. I was wondering if you could explain how the lazy-loading works because currently, I've got 133 plugins configured using lazy.nvim, and neovim takes about 130 milliseconds to load.

I was wondering if you could break down your neovim structure and explain what each file does, and how the plugins are loaded such that, with all the plugins you have (150+), it still loads in about 80 milliseconds.

PS: I really love all your plugins, especially **navigator.nvim**. Thanks for all your hard work! :)

**Comment by ray-x** [comment]
The loading time as I tested is 93ms. As I enabled debug logs so it should be quick if logs are disabled.

I think the key part of my setup
1> most of the plugins are lazy loaded. 
e.g.
```lua
editor["ggandor/leap.nvim"] = {
  opt = true,  -- do not load leap
  module = "leap",  -- until require'leap' is called
 }

-- or
editor["rrethy/vim-hexokinase"] = {
  config = conf.hexokinase,
  opt = true,    -- do not load vim-hexokinase
  cmd = { "HexokinaseTurnOn", "HexokinaseToggle" },   -- until Hexokxxxx is called
}
```

2> Also some of the plugin are opt only; they are loaded in `lua/core/lazy.lua` When the neovim is fully loaded
Basically, I manually load those plugins
e.g.
```lua
    loader("neogen")
    loader("hlargs.nvim")
```

Last but not least, always use check which script slows you down.
```
nvim   filename  --startuptime   vim.log
```

**Comment by SingularisArt** [comment]
Alright. Thanks! Using those tips, I was able to bring my load time down to about 90 milliseconds! Thanks mate!
Also, quick question. Why don't you use [lazy.nvim](https://github.com/folke/lazy.nvim)? He's built it with the intention of making it fast. You don't even need the `impatient.nvim` plugin anymore.

**Comment by SingularisArt** [comment]
Alright. So, here's the outcome of my replication of your setup (kinda):

https://user-images.githubusercontent.com/57925294/209402641-fff1dfb9-8626-49ea-8d10-f9be41cd9f21.mp4

But according to [vim-startuptime](https://github.com/dstein64/vim-startuptime), it takes neovim 95 milliseconds to load. Do you know what's causing this issue? Here's the link to my [plugins.lua](https://github.com/SingularisArt/Singularis/blob/master/aspects/nvim/files/.config/nvim/lua/SingularisArt/plugins.lua) and [lazy.lua](https://github.com/SingularisArt/Singularis/blob/master/aspects/nvim/files/.config/nvim/lua/SingularisArt/lazy.lua).

**Comment by ray-x** [comment]
For me 95ms is pretty good already.
Did you try  `impatient`, it save me about 10~20ms on boot as I recalled.
Also my nvim will load galaxy.lua which is a lightweight color scheme that normally saves me 2ms.
One last thing, does lazy provides a way to compile the init.lua into a compiled version like `PackerCompile`

**Comment by folke** [comment]
@SingularisArt you should not be doing that thing in `lazy.lua`. That way you're basically removing any benefit of using lazy :) Check the docs.

Lazy includes byte compilation and caching which is faster than impatient.

There's also no need for a compile step. Everything happens on the fly and should be quite a bit faster than with Packer.

**Comment by ray-x** [comment]
[vim.log](https://github.com/ray-x/nvim/files/10316790/vim.log)
@SingularisArt 
I uploaded a startup log for your reference. It loaded a lua file of ~200 lines and took 72ms to start.
The way my nvim setup are different compared to lazy.nvim. My setup relies on packer and impatient; it needs manual tuning.

**Comment by SingularisArt** [comment]
@ray-x Thanks for the log file. Yeah, whenever I started to load more plugins in, I started to see the effect on the speed.
@folke How would you recommend someone to load plugins? Could you describe how your neovim structure works and how you load plugins using `lazy.nvim`?

**Comment by folke** [comment]
It's all in the lazy docs. Check the section on structuring your plugins. There's also links there to my own dots
