### ISSUE TITLE
Many Installation Errors

### ISSUE THREAD

**Issue by OmarElKhatibCS** [ray-x/nvim#3]
Hello Can you provide more details on how to install this ,
 ✗ Failed to install /home/omar/github/zephyr-nvim
 ✗ Failed to install /home/omar/github/lsp_signature.nvim
some plugins mapping to my local those failing directly and many other errors.
Also in the repo there is this https://github.com/ray-x/nvim/blob/master/pluginrc.d
the content is hard coded path to your local machine
I am running on Fedora 34 and NeoVim 0.6.0~nightly

Can you please provide a more clear instructions or a youtube video , or a script.
EDIT : I updated from 0.5.0 to 0.6.0 ~ nightly because treesitter said so

**Comment by OmarElKhatibCS** [comment]
I installed all other plugins after spamming `PackerInstall` `PackerUpdate` `PackerClean` there is still those hardcoded plugins

 ✗ Failed to install /home/omar/github/aurora
 ✗ Failed to install /home/omar/github/zephyr-nvim
 ✗ Failed to install /home/omar/github/lsp_signature.nvim
 ✗ Failed to install /home/omar/github/navigator.lua
 ✗ Failed to install /home/omar/github/go.nvim
 ✗ Failed to install /home/omar/github/guihua.lua
 ✗ Failed to install /home/omar/github/cmp-treesitter
 ✗ Failed to install /home/omar/github/material_plus.nvim

**Comment by OmarElKhatibCS** [comment]
I fixed the problem by making an github folder in the $HOME and cloning all those errors from your repo , but it's still weird that I need to manually make an github folder and clone them their , It's better if they are directly pulled from your github.
Also you should mention this in the README
Still this also Don't know what is for : https://github.com/ray-x/nvim/blob/master/pluginrc.d

**Comment by OmarElKhatibCS** [comment]
Error detected while processing InsertEnter Autocommands for "<buffer=1>":
E5108: Error executing lua ...er/start/lsp_signature.nvim/lua/lsp_signature_helper.lua:30: bad argument #1 to 'close' (FILE* expected, g
ot nil)

Got this error while editing a go code also there is no autcomplete 
![image](https://user-images.githubusercontent.com/35725554/135340766-3787dea0-31ea-4385-8fac-bb7fcfd33980.png)
and got this one when I press i to edit
![image](https://user-images.githubusercontent.com/35725554/135340820-c26b7ea3-0b7a-4f0a-a03d-34da4e5d074f.png)
and there is no autocomplete + weird screen glitches
![image](https://user-images.githubusercontent.com/35725554/135340957-0019d35d-16ca-4f84-aad7-6f31f0012215.png)

and when I open just `nvim` and press i , I got this 
![image](https://user-images.githubusercontent.com/35725554/135341024-ba3b938a-0405-4c26-8854-f6123f2c83b8.png)

Too many effort to make this work I hope you can help me , I like the final result in your videos.

**Comment by ray-x** [comment]
Hi, @OmarElKhatibCS 
Thanks for try the setup out

Most of the failed plugins are developed/forked by me and stored locally. 
pluginrc.d is no longer used (that was for Plug setup). I deleted in the new version.

Please update the repo. I added a helper function so if HOST_NAME does not point to my machine, it will load the plugins from github.

I did not see coq errors in my setup. It should be disabled by default. Please try the new version and check if you still see the errors.

Thanks!

**Comment by OmarElKhatibCS** [comment]
I cleared .config/nvim and .local/share/nvim and download new changes
now works fine with some errors in launch spammed "Enter" and many restarts , still this error every time I need to edit a fix is to check nil as I said before but I don't know if this log is necessary

![image](https://user-images.githubusercontent.com/35725554/135472557-d64363af-93bf-4cbf-ae0d-74384c989f38.png)

**Comment by OmarElKhatibCS** [comment]
![image](https://user-images.githubusercontent.com/35725554/135473818-cfbaedfc-fdd1-4abf-89fb-9acbf61da935.png)
also some icons are missing not all of them
![image](https://user-images.githubusercontent.com/35725554/135474003-ff619819-8b13-48f0-88ce-6f13029bb74d.png)

**Comment by ray-x** [comment]
Are you using one of the nerd font from: https://www.nerdfonts.com/
I am currently using VictorMono downloaded from  https://www.nerdfonts.com/ 

Also. Seems I will need to disable the debug output in release version.
You may get loads of logs and it will slow you down

**Comment by OmarElKhatibCS** [comment]
![image](https://user-images.githubusercontent.com/35725554/135494338-4e0c58b8-64f0-46d0-a6a0-6ef9002e99c0.png)

I downloaded mentioned fonts they are flat I think because I am on Linux.
I think all problem fixed :D

Sorry for bothering you with my issue .
Thanks for this superior VIM setup

**Comment by ray-x** [comment]
Great!

**Comment by OmarElKhatibCS** [comment]
Can you please tell me what file/folder responsible to install themes also :set bg=dark 
Also where I can find the key binds please.
Then we can close this issue.
