### ISSUE TITLE
Old files live in the repo

### ISSUE THREAD

**Issue by OmarElKhatibCS** [ray-x/nvim#4]
Can you please tell me what file/folder responsible to install themes also :set bg=dark and others , I tried to edit vimrc but it doesnt take changes , I even deleted the file and doesnt affect the setup.
I think cleaning old unused files will make the repo cleaner and easier for new comers like me and others that watch your youtube videos.
Also where I can find the key binds please.

**Comment by OmarElKhatibCS** [comment]
I suggest tagging the repo with 
```bash
git tag 1.0.0
```
then remove unused files , then tag it with 
```bash
git tag 2.0.0
```
like this you don't loose old files.

**Comment by ray-x** [comment]
The theme install and config is in` lua/modules/ui` folder
Plugins.lua : the theme plugins to be install
Config.lua:    config the plugins


The theme is loaded using the following codes:

```
local themes = {
  "material_plus.nvim", "aurora", "aurora", "tokyonight.nvim", "material_plus.nvim", "aurora",
  "zephyr-nvim", "gruvbox-material", "sonokai", "github-nvim-theme"
}
if plugin_folder() == [[~/github/]] then
  -- debug the color theme
  themes = {"material_plus.nvim"}
end
local v = math.random(1, #themes)
local loading_theme = themes[v]

local cmd = [[au VimEnter * ++once lua require("packer.load")({']] .. loading_theme
                .. [['}, { event = "VimEnter *" }, _G.packer_plugins)]]
vim.cmd(cmd)
```

`aurora`, `material_plus` was used in my video. But other themes are also very good.

Keymap is defined in `lua/core/keymap` , `lua/core/mapping.lua` and `lua/overwrite` mapping.

The first is keymap for nvim, second is more for core plugins, the 3rd one is self defined(as I used to sync the repo with other repos and normally I re-map key in this folder)

**Comment by OmarElKhatibCS** [comment]
Yes it works still having hardtime config stuff by myself like I successfully installed moonlight , but when I say 
```lua
local themes = {
  "moonlight.nvim", "material_plus.nvim", "aurora", "aurora", "tokyonight.nvim", "material_plus.nvim", "aurora",
  "zephyr-nvim", "gruvbox-material", "sonokai", "github-nvim-theme"
}
```
I tried also without the `.nvim`
```lua
local loading_theme = themes[1]
```
It doesnt load the theme.
I am new to Lua I think learning lua will answer a lot of answers.

**Comment by OmarElKhatibCS** [comment]
![image](https://user-images.githubusercontent.com/35725554/135659379-2e3fcbe5-6c46-47f1-a3ab-9c09db3c2965.png)
Also I would like to report this issue we probably should open an issue but I don't know which plugin it is.
When I auto-complete , let's say I didnt want help of plugin to fill all of them , and I fill them manually , next time I press `TAB` it move to next it is nice to make it that if user interrupt it it will delete suggestions and release `TAB` or just show a box of what they are without filling them.

**Comment by ray-x** [comment]
If you are using moonlight.nvim config as well. Follow the example of `sainnhe/sonokai`

you need
```lua
ui["moonlight.nvim"] = {
setup = function()
   -- setup before theme loaded
  vim.g.moonlight_italic_comments = true
  vim.g.moonlight_italic_keywords = true 
end,
config = function()
  require('moonlight').set()  -- the scheme need enabled here in config func
end
}
```


As for the lsp-signature issue you mentioned. It is expected.  The reason is that `nvim-cmp` snippet inserted text that can not be parsed correctly by gopls.   It confused gopls and gopls sent back incorrect response.
