### ISSUE TITLE
Error on starting

### ISSUE THREAD

**Issue by nexusstar** [ray-x/nvim#5]
I am receiving the following error on starting:
```
github-nvim-theme
Error detected while processing /home/nexus/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/nexus/.config/nvim/lua/core/options.lua:138: Vim(source):E48
Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:9: attempt to inde
x local 'plugins' (a nil value)
```
I've checked and all the plugins are installed could you please tell me what could be the problem?

**Comment by ray-x** [comment]
Did you have github-nvim-theme installed? Should be in your `~/.local/share/nvim/site/pack/packer/opt` folder
If not, 
Try `PackerCompile` and `PackerInstall`. 
You may need to restart nvim a few times during the setup.

**Comment by nexusstar** [comment]
@ray-x Thank you for your answer and your awesome config :)  it turns out that I've messed up my install of neovim I've reinstalled all from source and all works
