### ISSUE TITLE
Color scheme lazy loading

### ISSUE THREAD

**Issue by ryantking** [ray-x/nvim#7]
Would you be able to elaborate a little bit on how your color scheme loading mechanism works?

Looking at the code, it looks like when you load the UI config file, a color scheme is randomly chosen then attached to the `VimEnter` startup event. What I don't understand is two things:

1. Is moving a plugin to the `VimEnter` event a startup optimization? It was my understanding that `VimEnter` happens before the UI is first drawn so there is no speedup by moving a plugin from start to that event.
2. What does [this](https://github.com/ray-x/nvim/blob/master/lua/core/lazy.lua#L106) do? It looks like the `ColorScheme` event is triggered when the color scheme is changed, which happens in the `VimEnter` event when a color scheme is set.

What I think would make sense is deferring the loading/setting of a color scheme, but that doesn't look like what the code does?

**Comment by ray-x** [comment]
VimEnter is a trigger to randomize and load color scheme, not for startup time optimisation.  You can load everything before or after this event. 

e.g. You can set 

```
local cmd = [[au ColorScheme * ++once lua require("packer.load")({']] .. loading_theme
                .. [['}, { event = "ColorScheme *" }, _G.packer_plugins)]]
```

But if you set this, you will see a color transition from default to a setup color scheme.

Why a separate ColorScheme event:
The reason behind is treesitter (if enabled) is lazy loading. So when first time colorscheme loaded, treesitter may not ready (for a large file).  That is why a colorschem event triggering a redraw based on loaded color scheme.

Hope it explain you questions.
