### ISSUE TITLE
Resetting leader in overwrite folder unmaps previous maps

### ISSUE THREAD

**Issue by BeauSLM** [ray-x/nvim#9]
Reset my leader key (to space in my case) in lua/overwrite/mapping.lua unsets maps made in other files - namely lua/keymap/init.lua and lua/modules/lang/dap/init.lua.

from dap/init.lua:
![image](https://user-images.githubusercontent.com/63375392/142262910-3579a35a-432b-4e3a-888c-64d5eca16f50.png)
![image](https://user-images.githubusercontent.com/63375392/142262946-03be2af7-f0ed-4b24-bf70-0c8b09dfa1f2.png)

from keymap/init.lua
![image](https://user-images.githubusercontent.com/63375392/142263073-41988e80-5534-407c-8541-531dfe3e6392.png)
![image](https://user-images.githubusercontent.com/63375392/142263108-6b770832-ebba-4c6a-b1b2-23f0f383d08f.png)

I've found two fixes:
1. Comment out the mapleader reset in overwrite/mapping.lua
2. If the leader key set in core/init.lua is the same as the leader key set in overwrite/mapping.lua, this isn't an issue (i.e. if you're not resetting the leaderkey in overwrite).

**Comment by ray-x** [comment]
Yes it should be removed. I update the code.
The sequence:
1) core keymap
2) plugin keymap
3) overwrite

Overwrite should not overwrite the leader map again

**Comment by BeauSLM** [comment]
I briefly tested, it works fine as far as I can tell
